FROM golang:1.13.1 as builder
RUN mkdir /build
WORKDIR /build
COPY go.* ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/server/main.go

FROM alpine:3.10  
WORKDIR /
RUN wget https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.0/grpc_health_probe-linux-amd64
RUN mv grpc_health_probe-linux-amd64 /usr/bin/grpc_health_probe
RUN chmod 755 /usr/bin/grpc_health_probe
COPY --from=builder /build/main /todomanager
CMD ["/todomanager"]
