FROM golang:1.13.1 as builder
RUN mkdir /build
WORKDIR /build
COPY go.* ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/server/main.go

FROM alpine:3.10  
WORKDIR /
COPY --from=builder /build/main /apiserver
CMD ["/apiserver"]
