{
 "title": "Giantswarm Todo App",
 "time": { "from": "2020-07-23T10:22:11.131Z", "to": "2020-07-23T10:26:04.485Z" },
 "panels": [
  {
   "title": "Top 10 client's request rate for \"get all todos\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(sum by (user)(todo_get_all_count_total)[5m:]))",
     "legendFormat": "user={{user}}"
    }
   ]
  },
  {
   "title": "Request percentage by HTTP code and method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code,method) (increase(http_requests_total{path=~\"/v1/.+\", container=\"apiserver\"}[1m])) / ignoring(code,method) group_left sum(increase(http_requests_total{path=~\"/v1/.+\", container=\"apiserver\"}[1m]))",
     "legendFormat": "{{method}}-{{code}}"
    }
   ]
  },
  {
   "title": "All requests response time distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(http_request_duration_seconds_bucket{container=\"apiserver\", path=~\"/v1/.*\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}